/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponentA {
    }
    interface MyComponentB {
    }
}
declare global {
    interface HTMLMyComponentAElement extends Components.MyComponentA, HTMLStencilElement {
    }
    var HTMLMyComponentAElement: {
        prototype: HTMLMyComponentAElement;
        new (): HTMLMyComponentAElement;
    };
    interface HTMLMyComponentBElement extends Components.MyComponentB, HTMLStencilElement {
    }
    var HTMLMyComponentBElement: {
        prototype: HTMLMyComponentBElement;
        new (): HTMLMyComponentBElement;
    };
    interface HTMLElementTagNameMap {
        "my-component-a": HTMLMyComponentAElement;
        "my-component-b": HTMLMyComponentBElement;
    }
}
declare namespace LocalJSX {
    interface MyComponentA {
    }
    interface MyComponentB {
    }
    interface IntrinsicElements {
        "my-component-a": MyComponentA;
        "my-component-b": MyComponentB;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-a": LocalJSX.MyComponentA & JSXBase.HTMLAttributes<HTMLMyComponentAElement>;
            "my-component-b": LocalJSX.MyComponentB & JSXBase.HTMLAttributes<HTMLMyComponentBElement>;
        }
    }
}
